[package]
name = "warp_cli"
edition = "2024"
description = "CLI argument parsing for Warp"
authors.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
cfg-if = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
url = { workspace = true, features = ["serde"] }
warp_core = { path = "../warp_core" }
warp_util = { path = "../warp_util" }
color-print = "0.3"
clap_complete = "4.5.58"
anyhow.workspace = true
local_control.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation"
] }

[build-dependencies]
cfg_aliases.workspace = true

[features]
integration_tests = []


[dev-dependencies]
warp_core = { workspace = true, features = ["test-util"] }
