use std::path::Path;

use super::*;
use crate::terminal::cli_agent::CLIAgent;

fn generated_worktree_path_string(repo: &str, worktree_name: &str) -> String {
    super::super::tab_config::generated_worktree_path(Path::new(repo), worktree_name)
        .display()
        .to_string()
}

// ── SessionType helpers ──

#[test]
fn terminal_command_prefix_is_none() {
    assert_eq!(SessionType::Terminal.command_prefix(), None);
}

#[test]
fn oz_command_prefix_is_none() {
    assert_eq!(SessionType::Oz.command_prefix(), None);
}

#[test]
fn cli_agent_command_prefix_delegates() {
    assert_eq!(
        SessionType::CliAgent(CLIAgent::Claude).command_prefix(),
        Some("claude")
    );
    assert_eq!(
        SessionType::CliAgent(CLIAgent::Codex).command_prefix(),
        Some("codex")
    );
    assert_eq!(
        SessionType::CliAgent(CLIAgent::Gemini).command_prefix(),
        Some("gemini")
    );
}

// ── build_tab_config ──

#[test]
fn terminal_no_worktree() {
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/project"),
        false,
        true,
    );

    assert_eq!(config.name, "New tab: project");
    assert!(config.title.is_none());
    assert_eq!(config.panes.len(), 1);
    assert_eq!(
        config.panes[0].directory.as_deref(),
        Some("/home/user/project")
    );
    assert!(config.panes[0].commands.is_none());
    assert!(config.params.is_empty());
}

#[test]
fn cli_agent_no_worktree() {
    let config = build_tab_config(
        &SessionType::CliAgent(CLIAgent::Claude),
        Path::new("/home/user/project"),
        false,
        true,
    );

    assert_eq!(config.panes[0].commands.as_deref().unwrap(), &["claude"]);
    assert!(config.params.is_empty());
    assert!(config.title.is_none());
}

#[test]
fn terminal_with_worktree() {
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/repo"),
        true,
        false,
    );

    assert_eq!(config.title.as_deref(), Some("{{worktree_branch_name}}"));
    let expected_worktree_path =
        generated_worktree_path_string("/home/user/repo", "{{worktree_branch_name}}");
    assert_eq!(
        config.panes[0].commands.as_deref().unwrap(),
        [
            format!(
                "git worktree add -b {{{{worktree_branch_name}}}} \"{expected_worktree_path}\""
            ),
            format!("cd \"{expected_worktree_path}\""),
        ]
        .as_ref()
    );
    assert!(!config.uses_autogenerated_branch_name());
    assert!(config.params.contains_key("worktree_branch_name"));
    let param = &config.params["worktree_branch_name"];
    assert_eq!(param.param_type, TabConfigParamType::Text);
    assert_eq!(param.default.as_deref(), Some("my-feature-branch"));
}

#[test]
fn cli_agent_with_worktree() {
    let config = build_tab_config(
        &SessionType::CliAgent(CLIAgent::Gemini),
        Path::new("/home/user/repo"),
        true,
        false,
    );

    // Worktree commands come first, then agent command.
    let expected_worktree_path =
        generated_worktree_path_string("/home/user/repo", "{{worktree_branch_name}}");
    assert_eq!(
        config.panes[0].commands.as_deref().unwrap(),
        [
            format!(
                "git worktree add -b {{{{worktree_branch_name}}}} \"{expected_worktree_path}\""
            ),
            format!("cd \"{expected_worktree_path}\""),
            "gemini".to_string(),
        ]
        .as_ref()
    );
    assert!(config.params.contains_key("worktree_branch_name"));
    assert_eq!(config.title.as_deref(), Some("{{worktree_branch_name}}"));
}

#[test]
fn oz_no_worktree_same_as_terminal() {
    let oz = build_tab_config(
        &SessionType::Oz,
        Path::new("/home/user/project"),
        false,
        true,
    );
    let terminal = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/project"),
        false,
        true,
    );

    assert_eq!(oz.panes[0].directory, terminal.panes[0].directory);
    assert_eq!(oz.panes[0].commands, terminal.panes[0].commands);
    assert_eq!(oz.params.len(), terminal.params.len());
}

#[test]
fn oz_with_worktree_has_worktree_commands_but_no_agent_command() {
    let config = build_tab_config(&SessionType::Oz, Path::new("/home/user/repo"), true, false);
    let expected_worktree_path =
        generated_worktree_path_string("/home/user/repo", "{{worktree_branch_name}}");

    assert_eq!(
        config.panes[0].commands.as_deref().unwrap(),
        [
            format!(
                "git worktree add -b {{{{worktree_branch_name}}}} \"{expected_worktree_path}\""
            ),
            format!("cd \"{expected_worktree_path}\""),
        ]
        .as_ref()
    );
    assert!(config.params.contains_key("worktree_branch_name"));
}

#[test]
fn directory_path_is_absolute_in_directory() {
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/absolute/path/here"),
        false,
        true,
    );

    let directory = config.panes[0].directory.as_deref().unwrap();
    assert!(
        directory.starts_with('/'),
        "directory should be absolute, got: {directory}"
    );
}

// ── TOML round-trip ──

#[test]
fn round_trip_terminal_no_worktree() {
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/project"),
        false,
        true,
    );
    let toml_str = toml::to_string_pretty(&config).expect("Should serialize");
    let parsed: TabConfig = toml::from_str(&toml_str).expect("Should deserialize");

    assert_eq!(parsed.name, config.name);
    assert_eq!(parsed.panes[0].directory, config.panes[0].directory);
    assert_eq!(parsed.panes[0].commands, config.panes[0].commands);
}

#[test]
fn round_trip_cli_agent_with_worktree() {
    let config = build_tab_config(
        &SessionType::CliAgent(CLIAgent::Claude),
        Path::new("/home/user/repo"),
        true,
        false,
    );
    let toml_str = toml::to_string_pretty(&config).expect("Should serialize");
    let parsed: TabConfig = toml::from_str(&toml_str).expect("Should deserialize");

    assert_eq!(parsed.name, config.name);
    assert_eq!(parsed.title, config.title);
    assert_eq!(parsed.panes[0].commands, config.panes[0].commands);
    assert!(parsed.params.contains_key("worktree_branch_name"));
    assert_eq!(
        parsed.params["worktree_branch_name"].default.as_deref(),
        Some("my-feature-branch")
    );
}

// ── render_tab_config integration ──

#[test]
fn render_terminal_produces_correct_pane_template() {
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/project"),
        false,
        true,
    );
    let param_values = config.default_param_values();
    let (title, pane_template) = super::super::render_tab_config(&config, &param_values, None);

    assert!(title.is_none());
    if let crate::launch_configs::launch_config::PaneTemplateType::PaneTemplate {
        cwd,
        commands,
        ..
    } = pane_template
    {
        assert_eq!(cwd, std::path::PathBuf::from("/home/user/project"));
        assert!(commands.is_empty());
    } else {
        panic!("Expected PaneTemplate variant");
    }
}

#[test]
fn render_cli_agent_produces_correct_commands() {
    let config = build_tab_config(
        &SessionType::CliAgent(CLIAgent::Claude),
        Path::new("/home/user/project"),
        false,
        true,
    );
    let param_values = config.default_param_values();
    let (_, pane_template) = super::super::render_tab_config(&config, &param_values, None);

    if let crate::launch_configs::launch_config::PaneTemplateType::PaneTemplate {
        commands, ..
    } = pane_template
    {
        assert_eq!(commands.len(), 1);
        assert_eq!(commands[0].exec, "claude");
    } else {
        panic!("Expected PaneTemplate variant");
    }
}

#[test]
fn render_worktree_substitutes_default_branch_name() {
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/repo"),
        true,
        false,
    );
    let param_values = config.default_param_values();
    let (title, pane_template) = super::super::render_tab_config(&config, &param_values, None);

    assert_eq!(title.as_deref(), Some("my-feature-branch"));
    if let crate::launch_configs::launch_config::PaneTemplateType::PaneTemplate {
        commands, ..
    } = pane_template
    {
        assert!(commands[0].exec.contains("my-feature-branch"));
        assert!(commands[1].exec.contains("my-feature-branch"));
    } else {
        panic!("Expected PaneTemplate variant");
    }
}

// ── write_tab_config (file naming) ──

#[test]
fn write_tab_config_creates_file_with_correct_naming() {
    let dir = tempfile::tempdir().expect("Should create temp dir");
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/project"),
        false,
        true,
    );

    let path1 = write_tab_config(&config, dir.path(), "startup_config")
        .expect("First write should succeed");
    assert_eq!(path1.file_name().unwrap(), "startup_config.toml");

    let path2 = write_tab_config(&config, dir.path(), "startup_config")
        .expect("Second write should succeed");
    assert_eq!(path2.file_name().unwrap(), "startup_config_1.toml");

    let path3 = write_tab_config(&config, dir.path(), "startup_config")
        .expect("Third write should succeed");
    assert_eq!(path3.file_name().unwrap(), "startup_config_2.toml");
}

#[test]
fn write_tab_config_content_is_valid_toml() {
    let dir = tempfile::tempdir().expect("Should create temp dir");
    let config = build_tab_config(
        &SessionType::CliAgent(CLIAgent::Claude),
        Path::new("/home/user/repo"),
        true,
        false,
    );

    let path =
        write_tab_config(&config, dir.path(), "startup_config").expect("Write should succeed");
    let contents = std::fs::read_to_string(&path).expect("Should read file");
    let parsed: TabConfig = toml::from_str(&contents).expect("Should parse as TabConfig");

    assert_eq!(parsed.name, "Worktree: repo");
    assert_eq!(parsed.panes[0].commands.as_ref().unwrap().len(), 3);
    assert!(parsed.params.contains_key("worktree_branch_name"));
}

#[test]
fn write_tab_config_creates_directory_if_missing() {
    let dir = tempfile::tempdir().expect("Should create temp dir");
    let nested = dir.path().join("nested").join("tab_configs");
    let config = build_tab_config(&SessionType::Terminal, Path::new("/tmp"), false, true);

    let path = write_tab_config(&config, &nested, "startup_config").expect("Write should succeed");
    assert!(path.exists());
}

#[test]
fn write_tab_config_custom_base_name() {
    let dir = tempfile::tempdir().expect("Should create temp dir");
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/project"),
        false,
        true,
    );

    let path =
        write_tab_config(&config, dir.path(), "my_tab_config").expect("Write should succeed");
    assert_eq!(path.file_name().unwrap(), "my_tab_config.toml");
}

#[test]
fn terminal_with_autogenerated_worktree() {
    let config = build_tab_config(
        &SessionType::Terminal,
        Path::new("/home/user/repo"),
        true,
        true,
    );

    assert!(config.title.is_none());
    let expected_worktree_path =
        generated_worktree_path_string("/home/user/repo", "{{autogenerated_branch_name}}");
    assert_eq!(
        config.panes[0].commands.as_deref().unwrap(),
        [
            format!(
                "git worktree add -b {{{{autogenerated_branch_name}}}} \"{expected_worktree_path}\""
            ),
            format!("cd \"{expected_worktree_path}\""),
        ]
        .as_ref()
    );
    assert!(config.uses_autogenerated_branch_name());
    assert!(config.params.is_empty());
}

// ── tab_config_from_pane_snapshot ──

// ── snapshot pane_type derivation ──

// ── nested / multi-level pane layout edge cases ──

// ── is_git_repo ──

#[test]
fn detects_git_repo_with_dot_git_dir() {
    let dir = tempfile::tempdir().expect("Should create temp dir");
    std::fs::create_dir(dir.path().join(".git")).expect("Should create .git dir");

    assert!(is_git_repo(dir.path()));
}

#[test]
fn detects_non_git_directory() {
    let dir = tempfile::tempdir().expect("Should create temp dir");

    assert!(!is_git_repo(dir.path()));
}

#[test]
fn detects_git_repo_in_parent() {
    let dir = tempfile::tempdir().expect("Should create temp dir");
    std::fs::create_dir(dir.path().join(".git")).expect("Should create .git dir");
    let subdir = dir.path().join("src");
    std::fs::create_dir(&subdir).expect("Should create subdir");

    assert!(is_git_repo(&subdir));
}

#[test]
fn root_directory_does_not_loop() {
    // Ensures the walk terminates at the filesystem root without panicking.
    assert!(!is_git_repo(Path::new("/")));
}
